server:
  port: 15110
eureka:
  instance:
    hostname: 192.168.1.201
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/